### ISSUE TITLE
geolite.maxmind.com

### ISSUE THREAD

**Issue by dereitz** [lephisto/pfsense-analytics#15]
Is anyone else seeing this error and happen to know the fix?  I'm guessing it is due to the recent MaxMind sign-in requirement, but haven't dug into the script to figure out how to fix yet.

  ```
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: geolite.maxmind.com
tar (child): /etc/graylog/server/mm.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
ERROR: Service 'graylog' failed to build: The command '/bin/sh -c chmod +x /etc/graylog/server/getGeo.sh && /etc/graylog/server/getGeo.sh' returned a non-zero code: 2
```

**Comment by dereitz** [comment]
Luckily, this turned out to be a fairly easy fix.  In pfsense-analytics/Docker/graylog/getGeo.sh, update the curl line to use the following syntax:

`curl --output /etc/graylog/server/mm.tar.gz 'https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=<license_key>&suffix=tar.gz'
`
Replace "<license_key>" with your own license key as obtained from maxmind.com.

**Comment by swizzlest** [comment]
Hey, thanks for this!  I updated the getgeo.sh and am a little further, but now receive a "gzip:stdin: not in gzip format before exit.  I'm not sure why, does anyone have any ideas?

**Comment by swizzlest** [comment]
I was using token key, not license.  Logging into maxmind, generating a license key and utilizing that instead fixed this.

**Comment by lephisto** [comment]
Fixed. Added Info to doc.

**Comment by prasket** [comment]
This is still an issue in the master branch. There is a PR to fix to new line but it was closed. 

https://github.com/lephisto/pfsense-analytics/pull/14

**Comment by lephisto** [comment]
Fixed in current version.
